create schema if not exists catalog;
create schema if not exists sales;
create schema if not exists app_auth;

create table if not exists catalog.products (
  id bigint generated by default as identity primary key,
  pt_ref text unique not null,
  description text not null,
  category text not null,
  brand_id text not null,
  created_at timestamptz default now()
);

create table if not exists sales.clients (
  id bigint generated by default as identity primary key,
  company_name text not null,
  contact_person text not null,
  created_by uuid not null references auth.users(id),
  created_at timestamptz default now(),
  status text not null check (status in ('pending', 'approved', 'rejected'))
);

create table if not exists sales.prices (
  id bigint generated by default as identity primary key,
  product_id bigint not null references catalog.products(id) on delete cascade,
  client_id bigint null references sales.clients(id) on delete cascade,
  currency text not null,
  min_qty int not null default 1,
  price numeric(12,2) not null,
  created_at timestamptz default now()
);

create table if not exists app_auth.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null check (role in ('admin', 'client'))
);

create table if not exists sales.quotes (
  id bigint generated by default as identity primary key,
  client_id bigint not null references sales.clients(id),
  requested_by uuid not null references auth.users(id),
  status text not null default 'requested' check (status in ('requested','approved','rejected')),
  created_at timestamptz default now()
);

create table if not exists sales.quote_items (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references sales.quotes(id) on delete cascade,
  product_id bigint not null references catalog.products(id),
  quantity int not null,
  unit_price numeric(12,2) not null,
  currency text not null
);

alter table catalog.products enable row level security;
alter table sales.clients enable row level security;
alter table sales.prices enable row level security;
alter table app_auth.profiles enable row level security;
alter table sales.quotes enable row level security;
alter table sales.quote_items enable row level security;

create policy "profiles own row" on app_auth.profiles
for select using (auth.uid() = id);

create policy "admin manages products" on catalog.products
for all using (exists (select 1 from app_auth.profiles p where p.id = auth.uid() and p.role = 'admin'));

create policy "client reads products" on catalog.products
for select using (true);

create policy "admin manages clients" on sales.clients
for all using (exists (select 1 from app_auth.profiles p where p.id = auth.uid() and p.role = 'admin'));

create policy "client own client row" on sales.clients
for select using (created_by = auth.uid());

create policy "admin manages prices" on sales.prices
for all using (exists (select 1 from app_auth.profiles p where p.id = auth.uid() and p.role = 'admin'));

create policy "client reads applicable prices" on sales.prices
for select using (
  client_id is null
  or exists (select 1 from sales.clients c where c.id = client_id and c.created_by = auth.uid())
);

create policy "admin manages quotes" on sales.quotes
for all using (exists (select 1 from app_auth.profiles p where p.id = auth.uid() and p.role = 'admin'));

create policy "client quote access" on sales.quotes
for select using (requested_by = auth.uid())
with check (requested_by = auth.uid());

create policy "admin manages quote items" on sales.quote_items
for all using (exists (select 1 from app_auth.profiles p where p.id = auth.uid() and p.role = 'admin'));

create policy "client quote items" on sales.quote_items
for select using (
  exists (select 1 from sales.quotes q where q.id = quote_id and q.requested_by = auth.uid())
);
